# -*- coding: utf-8 -*-
"""roadrush.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H_17oMJY4z4FPhNp55Sf7GfqJ5MH_9AB
"""

# Commented out IPython magic to ensure Python compatibility.
# YOLO inference
# %cd /content/drive/MyDrive/Hussle/

# !ls

# Commented out IPython magic to ensure Python compatibility.
# %pip install -q ultralytics

# !yolo task=detect mode=predict model="./best.pt" source='demo.mp4' show=False save=True